import {
  RiAddLine,
  RiAlertLine,
  RiArrowDownSLine,
  RiArrowGoBackLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowRightUpLine,
  RiBarChartLine,
  RiBox3Line,
  RiBuildingLine,
  RiCalculatorLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCloseLine,
  RiCodeSSlashLine,
  RiCornerDownLeftLine,
  RiFlashlightLine,
  RiGroupLine,
  RiHeadphoneLine,
  RiImageLine,
  RiInboxLine,
  RiLeafLine,
  RiLinksLine,
  RiMegaphoneLine,
  RiMenuLine,
  RiMessage3Line,
  RiPlayLine,
  RiReceiptLine,
  RiRefreshLine,
  RiRobotLine,
  RiRocketLine,
  RiSearchLine,
  RiSendPlaneLine,
  RiShoppingBagLine,
  RiSparklingLine,
  RiStackLine,
  RiTimeLine,
  RiTruckLine,
  RiVideoLine,
} from "@remixicon/react";

const icons = {
  "arrow-right": RiArrowRightLine,
  "arrow-up-right": RiArrowRightUpLine,
  "chevron-down": RiArrowDownSLine,
  "chevron-right": RiArrowRightSLine,
  plus: RiAddLine,
  search: RiSearchLine,
  inbox: RiInboxLine,
  menu: RiMenuLine,
  x: RiCloseLine,
  sparkles: RiSparklingLine,
  image: RiImageLine,
  video: RiVideoLine,
  message: RiMessage3Line,
  bag: RiShoppingBagLine,
  receipt: RiReceiptLine,
  truck: RiTruckLine,
  refresh: RiRefreshLine,
  bot: RiRobotLine,
  chart: RiBarChartLine,
  code: RiCodeSSlashLine,
  users: RiGroupLine,
  megaphone: RiMegaphoneLine,
  box: RiBox3Line,
  calc: RiCalculatorLine,
  headset: RiHeadphoneLine,
  leaf: RiLeafLine,
  rocket: RiRocketLine,
  building: RiBuildingLine,
  check: RiCheckLine,
  "check-circle": RiCheckboxCircleLine,
  alert: RiAlertLine,
  clock: RiTimeLine,
  undo: RiArrowGoBackLine,
  play: RiPlayLine,
  send: RiSendPlaneLine,
  layers: RiStackLine,
  link: RiLinksLine,
  zap: RiFlashlightLine,
  return: RiCornerDownLeftLine,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, className }: { name: IconName; className?: string }) {
  const Component = icons[name];
  return <Component className={className ? `icon ${className}` : "icon"} aria-hidden="true" focusable="false" />;
}
